using System;
using System.Collections.Generic;

namespace csc424_se2_organApp.Models
{
    public partial class CandLiin
    {
        public string CanAbo { get; set; }
        public decimal? CanAcademicLevel { get; set; }
        public decimal? CanAcademicProgress { get; set; }
        public string CanAcptA2Don { get; set; }
        public string CanAcptAboIncomp { get; set; }
        public string CanAcptExtracorpLi { get; set; }
        public string CanAcptHbcPos { get; set; }
        public string CanAcptHcvPos { get; set; }
        public string CanAcptLiSeg { get; set; }
        public string CanAcptOrgOtherTeam { get; set; }
        public string CanAcptProcurKi { get; set; }
        public string CanAcptProcurLi { get; set; }
        public string CanAcptProcurPa { get; set; }
        public DateTime? CanActivateDt { get; set; }
        public decimal? CanAgeAtListing { get; set; }
        public float? CanAgeInMonthsAtListing { get; set; }
        public float? CanAnastomosis { get; set; }
        public float? CanAnesthPriorDeath { get; set; }
        public decimal? CanAngina { get; set; }
        public decimal? CanAnginaCad { get; set; }
        public float? CanArtificialLi { get; set; }
        public string CanAscites { get; set; }
        public string CanBacteriaPerit { get; set; }
        public float? CanBmi { get; set; }
        public string CanCerebVasc { get; set; }
        public decimal? CanCitizenship { get; set; }
        public decimal? CanCognitiveDevelop { get; set; }
        public float? CanCtpScore { get; set; }
        public DateTime? CanDeathDt { get; set; }
        public decimal? CanDgn { get; set; }
        public decimal? CanDgn2 { get; set; }
        public string CanDgnOstxt { get; set; }
        public decimal? CanDiab { get; set; }
        public decimal? CanDiabTy { get; set; }
        public decimal? CanDial { get; set; }
        public string CanDrugTreatCopd { get; set; }
        public string CanDrugTreatHyperten { get; set; }
        public float? CanEcmo { get; set; }
        public decimal? CanEducation { get; set; }
        public string CanElectrolyte { get; set; }
        public decimal? CanEmplStat { get; set; }
        public string CanEnceph { get; set; }
        public DateTime? CanEndwlfu { get; set; }
        public string CanEthnicitySrtr { get; set; }
        public string CanExhaustVascAccess { get; set; }
        public float? CanFollowsOpoAlloc { get; set; }
        public decimal? CanFunctnStat { get; set; }
        public string CanFungalSepsis { get; set; }
        public string CanGender { get; set; }
        public float? CanHgtCm { get; set; }
        public DateTime? CanHgtWgtDt { get; set; }
        public float? CanIabp { get; set; }
        public decimal? CanInitActStatCd { get; set; }
        public DateTime? CanInitActStatDt { get; set; }
        public DateTime? CanInitInactStatDt { get; set; }
        public decimal? CanInitSrtrLabMeld { get; set; }
        public string CanInitSrtrLabMeldTy { get; set; }
        public decimal? CanInitStat { get; set; }
        public float? CanIvInotrop { get; set; }
        public DateTime? CanLastActStatDt { get; set; }
        public float? CanLastAlbumin { get; set; }
        public decimal? CanLastAscites { get; set; }
        public float? CanLastBili { get; set; }
        public string CanLastDialPriorWeek { get; set; }
        public decimal? CanLastEnceph { get; set; }
        public DateTime? CanLastInactStatDt { get; set; }
        public float? CanLastInr { get; set; }
        public float? CanLastSerumCreat { get; set; }
        public float? CanLastSerumSodium { get; set; }
        public decimal? CanLastSrtrLabMeld { get; set; }
        public string CanLastSrtrLabMeldTy { get; set; }
        public decimal? CanLastStat { get; set; }
        public string CanLifeSupport { get; set; }
        public float? CanLifeSupportOther { get; set; }
        public decimal? CanListingCtrId { get; set; }
        public DateTime? CanListingDt { get; set; }
        public decimal? CanListingOpoId { get; set; }
        public float? CanLivingDonTx { get; set; }
        public string CanLiDysfunctn { get; set; }
        public string CanLossVascAccess { get; set; }
        public string CanMalig { get; set; }
        public decimal? CanMaligTy { get; set; }
        public float? CanMaligTyBreast { get; set; }
        public float? CanMaligTyCnsTumor { get; set; }
        public float? CanMaligTyGenitourinary { get; set; }
        public float? CanMaligTyHepblast { get; set; }
        public float? CanMaligTyHepcarcinoma { get; set; }
        public float? CanMaligTyLeukLymph { get; set; }
        public float? CanMaligTyLiver { get; set; }
        public float? CanMaligTyLu { get; set; }
        public float? CanMaligTyOther { get; set; }
        public float? CanMaligTySkinMel { get; set; }
        public float? CanMaligTySkinNonMel { get; set; }
        public float? CanMaligTyThroat { get; set; }
        public float? CanMaligTyThyroid { get; set; }
        public float? CanMaligTyUnk { get; set; }
        public float? CanMaxAge { get; set; }
        public float? CanMaxMile { get; set; }
        public float? CanMaxWgt { get; set; }
        public decimal? CanMedCond { get; set; }
        public float? CanMinAge { get; set; }
        public float? CanMinWgt { get; set; }
        public float? CanMostRecentCreat { get; set; }
        public float? CanMostRecentHgtCm { get; set; }
        public float? CanMostRecentWgtKg { get; set; }
        public decimal? CanMotorDevelop { get; set; }
        public string CanMuscleWasting { get; set; }
        public string CanNeoplasm { get; set; }
        public string CanNewPrevPiTx { get; set; }
        public string CanNonReconGi { get; set; }
        public decimal? CanPepticUlcer { get; set; }
        public string CanPeriphVasc { get; set; }
        public string CanPermState { get; set; }
        public float? CanPge { get; set; }
        public decimal? CanPhyscCapacity { get; set; }
        public string CanPortalVein { get; set; }
        public string CanPrelimXmatchRequest { get; set; }
        public string CanPrevAbdomSurg { get; set; }
        public DateTime? CanPrevBoneMarrowDt { get; set; }
        public float? CanPrevBoneMarrowTx { get; set; }
        public float? CanPrevHl { get; set; }
        public float? CanPrevHr { get; set; }
        public float? CanPrevIn { get; set; }
        public float? CanPrevKi { get; set; }
        public float? CanPrevKp { get; set; }
        public float? CanPrevLi { get; set; }
        public float? CanPrevLu { get; set; }
        public float? CanPrevPa { get; set; }
        public float? CanPrevTx { get; set; }
        public string CanPrevTxfus { get; set; }
        public decimal? CanPrimaryPay { get; set; }
        public string CanPulmEmbol { get; set; }
        public decimal? CanRace { get; set; }
        public string CanRaceSrtr { get; set; }
        public string CanRecurSepsis { get; set; }
        public decimal? CanRemCd { get; set; }
        public decimal? CanRemCod { get; set; }
        public DateTime? CanRemDt { get; set; }
        public decimal? CanSecondaryPay { get; set; }
        public string CanSource { get; set; }
        public float? CanStatExtendFlg { get; set; }
        public DateTime? CanTiebreakerDt { get; set; }
        public string CanTipss { get; set; }
        public float? CanTotAlbumin { get; set; }
        public float? CanTotBili { get; set; }
        public float? CanTrrExists { get; set; }
        public decimal? CanTxCountry { get; set; }
        public decimal? CanVadTah { get; set; }
        public string CanVaricealBleeding { get; set; }
        public float? CanVentilator { get; set; }
        public float? CanWgtKg { get; set; }
        public string CanWorkIncome { get; set; }
        public decimal? CanWorkNoStat { get; set; }
        public decimal? CanWorkYesStat { get; set; }
        public float? CanYearEntryUs { get; set; }
        public decimal? DonorId { get; set; }
        public string DonTy { get; set; }
        public string OrgAr { get; set; }
        public decimal PersId { get; set; }
        public DateTime? PersNexttx { get; set; }
        public decimal? PersNexttxTrrId { get; set; }
        public DateTime? PersOptnDeathDt { get; set; }
        public DateTime? PersRestrictDeathDt { get; set; }
        public string PersRestrictDeathVrfy { get; set; }
        public DateTime? PersSsaDeathDt { get; set; }
        public decimal PxId { get; set; }
        public DateTime? RecTxDt { get; set; }
        public decimal? RecTxProcedureTy { get; set; }
        public string WlOrg { get; set; }
    }
}
