using System;
using System.Collections.Generic;

namespace csc424_se2_organApp.Models
{
    /// <summary>CandLiin Model</summary>
    /// <remarks>168 attributes for organ candidates.</remarks>
    public partial class CandLiin
    {
        public string CanAbo { get; set; }
        public decimal? CanAcademicLevel { get; set; }
        public decimal? CanAcademicProgress { get; set; }
        public string CanAcptA2Don { get; set; }
        public string CanAcptAboIncomp { get; set; }
        public string CanAcptExtracorpLi { get; set; }
        public string CanAcptHbcPos { get; set; }
        public string CanAcptHcvPos { get; set; }
        public string CanAcptLiSeg { get; set; }
        public string CanAcptOrgOtherTeam { get; set; }
        public string CanAcptProcurKi { get; set; }
        public string CanAcptProcurLi { get; set; }
        public string CanAcptProcurPa { get; set; }
        public DateTime? CanActivateDt { get; set; }
        public decimal? CanAgeAtListing { get; set; }
        public double? CanAgeInMonthsAtListing { get; set; }
        public decimal? CanAnastomosis { get; set; }
        public decimal? CanAnesthPriorDeath { get; set; }
        public decimal? CanAngina { get; set; }
        public decimal? CanAnginaCad { get; set; }
        public decimal? CanArtificialLi { get; set; }
        public string CanAscites { get; set; }
        public string CanBacteriaPerit { get; set; }
        public double? CanBmi { get; set; }
        public string CanCerebVasc { get; set; }
        public decimal? CanCitizenship { get; set; }
        public decimal? CanCognitiveDevelop { get; set; }
        public double? CanCtpScore { get; set; }
        public DateTime? CanDeathDt { get; set; }
        public decimal? CanDgn { get; set; }
        public decimal? CanDgn2 { get; set; }
        public string CanDgnOstxt { get; set; }
        public decimal? CanDiab { get; set; }
        public decimal? CanDiabTy { get; set; }
        public decimal? CanDial { get; set; }
        public string CanDrugTreatCopd { get; set; }
        public string CanDrugTreatHyperten { get; set; }
        public decimal? CanEcmo { get; set; }
        public decimal? CanEducation { get; set; }
        public string CanElectrolyte { get; set; }
        public decimal? CanEmplStat { get; set; }
        public string CanEnceph { get; set; }
        public DateTime? CanEndwlfu { get; set; }
        public string CanEthnicitySrtr { get; set; }
        public string CanExhaustVascAccess { get; set; }
        public decimal? CanFollowsOpoAlloc { get; set; }
        public decimal? CanFunctnStat { get; set; }
        public string CanFungalSepsis { get; set; }
        public string CanGender { get; set; }
        public double? CanHgtCm { get; set; }
        public DateTime? CanHgtWgtDt { get; set; }
        public decimal? CanIabp { get; set; }
        public decimal? CanInitActStatCd { get; set; }
        public DateTime? CanInitActStatDt { get; set; }
        public DateTime? CanInitInactStatDt { get; set; }
        public decimal? CanInitSrtrLabMeld { get; set; }
        public string CanInitSrtrLabMeldTy { get; set; }
        public decimal? CanInitStat { get; set; }
        public decimal? CanIvInotrop { get; set; }
        public DateTime? CanLastActStatDt { get; set; }
        public double? CanLastAlbumin { get; set; }
        public decimal? CanLastAscites { get; set; }
        public double? CanLastBili { get; set; }
        public string CanLastDialPriorWeek { get; set; }
        public decimal? CanLastEnceph { get; set; }
        public DateTime? CanLastInactStatDt { get; set; }
        public double? CanLastInr { get; set; }
        public double? CanLastSerumCreat { get; set; }
        public double? CanLastSerumSodium { get; set; }
        public decimal? CanLastSrtrLabMeld { get; set; }
        public string CanLastSrtrLabMeldTy { get; set; }
        public decimal? CanLastStat { get; set; }
        public string CanLifeSupport { get; set; }
        public decimal? CanLifeSupportOther { get; set; }
        public decimal? CanListingCtrId { get; set; }
        public DateTime? CanListingDt { get; set; }
        public decimal? CanListingOpoId { get; set; }
        public decimal? CanLivingDonTx { get; set; }
        public string CanLiDysfunctn { get; set; }
        public string CanLossVascAccess { get; set; }
        public string CanMalig { get; set; }
        public decimal? CanMaligTy { get; set; }
        public double? CanMaligTyBreast { get; set; }
        public double? CanMaligTyCnsTumor { get; set; }
        public double? CanMaligTyGenitourinary { get; set; }
        public double? CanMaligTyHepblast { get; set; }
        public double? CanMaligTyHepcarcinoma { get; set; }
        public double? CanMaligTyLeukLymph { get; set; }
        public double? CanMaligTyLiver { get; set; }
        public double? CanMaligTyLu { get; set; }
        public double? CanMaligTyOther { get; set; }
        public double? CanMaligTySkinMel { get; set; }
        public double? CanMaligTySkinNonMel { get; set; }
        public double? CanMaligTyThroat { get; set; }
        public double? CanMaligTyThyroid { get; set; }
        public double? CanMaligTyUnk { get; set; }
        public double? CanMaxAge { get; set; }
        public double? CanMaxMile { get; set; }
        public double? CanMaxWgt { get; set; }
        public decimal? CanMedCond { get; set; }
        public double? CanMinAge { get; set; }
        public double? CanMinWgt { get; set; }
        public double? CanMostRecentCreat { get; set; }
        public double? CanMostRecentHgtCm { get; set; }
        public double? CanMostRecentWgtKg { get; set; }
        public decimal? CanMotorDevelop { get; set; }
        public string CanMuscleWasting { get; set; }
        public string CanNeoplasm { get; set; }
        public string CanNewPrevPiTx { get; set; }
        public string CanNonReconGi { get; set; }
        public decimal? CanPepticUlcer { get; set; }
        public string CanPeriphVasc { get; set; }
        public string CanPermState { get; set; }
        public decimal? CanPge { get; set; }
        public decimal? CanPhyscCapacity { get; set; }
        public string CanPortalVein { get; set; }
        public string CanPrelimXmatchRequest { get; set; }
        public string CanPrevAbdomSurg { get; set; }
        public DateTime? CanPrevBoneMarrowDt { get; set; }
        public double? CanPrevBoneMarrowTx { get; set; }
        public double? CanPrevHl { get; set; }
        public double? CanPrevHr { get; set; }
        public double? CanPrevIn { get; set; }
        public double? CanPrevKi { get; set; }
        public double? CanPrevKp { get; set; }
        public double? CanPrevLi { get; set; }
        public double? CanPrevLu { get; set; }
        public double? CanPrevPa { get; set; }
        public double? CanPrevTx { get; set; }
        public string CanPrevTxfus { get; set; }
        public decimal? CanPrimaryPay { get; set; }
        public string CanPulmEmbol { get; set; }
        public decimal? CanRace { get; set; }
        public string CanRaceSrtr { get; set; }
        public string CanRecurSepsis { get; set; }
        public decimal? CanRemCd { get; set; }
        public decimal? CanRemCod { get; set; }
        public DateTime? CanRemDt { get; set; }
        public decimal? CanSecondaryPay { get; set; }
        public string CanSource { get; set; }
        public decimal? CanStatExtendFlg { get; set; }
        public DateTime? CanTiebreakerDt { get; set; }
        public string CanTipss { get; set; }
        public double? CanTotAlbumin { get; set; }
        public double? CanTotBili { get; set; }
        public double? CanTrrExists { get; set; }
        public decimal? CanTxCountry { get; set; }
        public decimal? CanVadTah { get; set; }
        public string CanVaricealBleeding { get; set; }
        public decimal? CanVentilator { get; set; }
        public double? CanWgtKg { get; set; }
        public string CanWorkIncome { get; set; }
        public decimal? CanWorkNoStat { get; set; }
        public decimal? CanWorkYesStat { get; set; }
        public double? CanYearEntryUs { get; set; }
        public decimal? DonorId { get; set; }
        public string DonTy { get; set; }
        public string OrgAr { get; set; }
        public decimal PersId { get; set; }
        public DateTime? PersNexttx { get; set; }
        public decimal? PersNexttxTrrId { get; set; }
        public DateTime? PersOptnDeathDt { get; set; }
        public DateTime? PersRestrictDeathDt { get; set; }
        public string PersRestrictDeathVrfy { get; set; }
        public DateTime? PersSsaDeathDt { get; set; }
        public decimal PxId { get; set; }
        public DateTime? RecTxDt { get; set; }
        public decimal? RecTxProcedureTy { get; set; }
        public string WlOrg { get; set; }
    }
}
