using System;
using System.Collections.Generic;

namespace csc424_se2_organApp.Models
{
    public partial class DonorLive
    {
        public int DonorId { get; set; }
        public int? DonA1 { get; set; }
        public int? DonA2 { get; set; }
        public string DonAbo { get; set; }
        public int? DonAge { get; set; }
        public int? DonAgeInMonths { get; set; }
        public int? DonAlbuminPostop { get; set; }
        public int? DonAlbuminPreop { get; set; }
        public int? DonAlkphosPostop { get; set; }
        public int? DonAlkphosPreop { get; set; }
        public string DonAnasthCompl { get; set; }
        public int? DonArrhythm { get; set; }
        public int? DonB1 { get; set; }
        public int? DonB2 { get; set; }
        public int? DonBiliPostop { get; set; }
        public int? DonBiliPreop { get; set; }
        public int? DonBpDischrgDiast { get; set; }
        public int? DonBpDischrgSyst { get; set; }
        public int? DonBpPostopDiast { get; set; }
        public int? DonBpPostopSyst { get; set; }
        public int? DonBpPreopDiast { get; set; }
        public int? DonBpPreopSyst { get; set; }
        public int? DonBw4 { get; set; }
        public int? DonBw6 { get; set; }
        public int? DonC1 { get; set; }
        public int? DonC2 { get; set; }
        public int? DonCancerFreeInterval { get; set; }
        public int? DonCitizenship { get; set; }
        public string DonCmv { get; set; }
        public string DonCmvClinical { get; set; }
        public string DonCmvCult { get; set; }
        public string DonCmvIgg { get; set; }
        public string DonCmvIgm { get; set; }
        public string DonCmvNucleic { get; set; }
        public string DonCmvTested { get; set; }
        public string DonDiab { get; set; }
        public int? DonDiabTreat { get; set; }
        public string DonDonation { get; set; }
        public int? DonDp1 { get; set; }
        public int? DonDp2 { get; set; }
        public int? DonDq1 { get; set; }
        public int? DonDq2 { get; set; }
        public int? DonDr1 { get; set; }
        public int? DonDr2 { get; set; }
        public int? DonDr51 { get; set; }
        public int? DonDr52 { get; set; }
        public int? DonDr53 { get; set; }
        public int? DonDurationAbstinence { get; set; }
        public string DonEbvClinical { get; set; }
        public string DonEbvDna { get; set; }
        public string DonEbvIgg { get; set; }
        public string DonEbvIgm { get; set; }
        public string DonEbvTested { get; set; }
        public int? DonEducation { get; set; }
        public string DonEthnicitySrtr { get; set; }
        public int? DonFefAfterPreop { get; set; }
        public int? DonFefBeforePreop { get; set; }
        public int? DonFev1AfterPreop { get; set; }
        public int? DonFev1BeforePreop { get; set; }
        public int? DonFfpUnits { get; set; }
        public string DonFree { get; set; }
        public int? DonFunctnStat { get; set; }
        public int? DonFvcAfterPreop { get; set; }
        public int? DonFvcBeforePreop { get; set; }
        public string DonGender { get; set; }
        public int? DonHaploTyMatch { get; set; }
        public string DonHbvAntibody { get; set; }
        public string DonHbvClinical { get; set; }
        public string DonHbvDna { get; set; }
        public string DonHbvHdv { get; set; }
        public string DonHbvLiHistology { get; set; }
        public string DonHbvSurfAntigen { get; set; }
        public string DonHbvTested { get; set; }
        public string DonHcvAntibody { get; set; }
        public string DonHcvClinical { get; set; }
        public string DonHcvLiHistology { get; set; }
        public string DonHcvRiba { get; set; }
        public string DonHcvRna { get; set; }
        public string DonHcvTested { get; set; }
        public string DonHealthInsur { get; set; }
        public int? DonHgtCm { get; set; }
        public int? DonHistCancer { get; set; }
        public string DonHistCigarette { get; set; }
        public int? DonHistHyperten { get; set; }
        public string DonHivAntibody { get; set; }
        public string DonHivClinical { get; set; }
        public string DonHivConfirm { get; set; }
        public string DonHivRna { get; set; }
        public string DonHivScreen { get; set; }
        public string DonHivTested { get; set; }
        public string DonHlaTyp { get; set; }
        public int? DonHlaTypNotDone { get; set; }
        public string DonHmoPpo { get; set; }
        public string DonHomeState { get; set; }
        public string DonHypertenDiet { get; set; }
        public string DonHypertenDiuretics { get; set; }
        public string DonHypertenOtherMeds { get; set; }
        public string DonHypertenPostop { get; set; }
        public int? DonInitDischrgDt { get; set; }
        public int? DonInrPostop { get; set; }
        public int? DonInrPreop { get; set; }
        public string DonIntraopCompl { get; set; }
        public int? DonIntraopComplReason { get; set; }
        public string DonKiBiopsy { get; set; }
        public int? DonKiCreatDischrg { get; set; }
        public int? DonKiCreatPostop { get; set; }
        public int? DonKiCreatPreop { get; set; }
        public string DonKiOtherCompl { get; set; }
        public int? DonKiOtherComplIntervention { get; set; }
        public string DonKiOtherIntervention { get; set; }
        public int? DonKiOtherInterventionDt { get; set; }
        public int? DonKiPctGs { get; set; }
        public string DonKiProcedureConvert { get; set; }
        public int? DonKiProcedureTy { get; set; }
        public string DonKiReadmit { get; set; }
        public int? DonKiReadmitDt { get; set; }
        public int? DonKiReadmitReason { get; set; }
        public string DonKiReop { get; set; }
        public int? DonKiReopBleen { get; set; }
        public int? DonKiReopBleenDt { get; set; }
        public int? DonKiReopBowel { get; set; }
        public int? DonKiReopBowelDt { get; set; }
        public int? DonKiReopHernia { get; set; }
        public int? DonKiReopHerniaDt { get; set; }
        public int? DonKiReopOther { get; set; }
        public int? DonKiReopOtherDt { get; set; }
        public int? DonKiReopVasc { get; set; }
        public int? DonKiReopVascDt { get; set; }
        public string DonKiVascCompl { get; set; }
        public int? DonKiVascComplIntervention { get; set; }
        public int? DonLengthHospStay { get; set; }
        public int? DonLivingDonCod { get; set; }
        public string DonLiBiliaryCompl { get; set; }
        public int? DonLiBiliaryComplGrade { get; set; }
        public string DonLiBiopsy { get; set; }
        public int? DonLiBiopsyMacroFat { get; set; }
        public int? DonLiBiopsyMicroFat { get; set; }
        public int? DonLiCreatPostop { get; set; }
        public int? DonLiCreatPreop { get; set; }
        public string DonLiOtherCompl { get; set; }
        public int? DonLiOtherComplIntervention { get; set; }
        public string DonLiOtherIntervention { get; set; }
        public int? DonLiOtherInterventionDt { get; set; }
        public int? DonLiProcedureTy { get; set; }
        public string DonLiReadmit { get; set; }
        public int? DonLiReadmitDt { get; set; }
        public int? DonLiReadmitReason { get; set; }
        public string DonLiReop { get; set; }
        public int? DonLiReopBiliary { get; set; }
        public int? DonLiReopBiliaryDt { get; set; }
        public int? DonLiReopBleed { get; set; }
        public int? DonLiReopBleedDt { get; set; }
        public int? DonLiReopBowel { get; set; }
        public int? DonLiReopBowelDt { get; set; }
        public int? DonLiReopFail { get; set; }
        public int? DonLiReopFailDt { get; set; }
        public int? DonLiReopHernia { get; set; }
        public int? DonLiReopHerniaDt { get; set; }
        public int? DonLiReopOther { get; set; }
        public int? DonLiReopOtherDt { get; set; }
        public int? DonLiReopVasc { get; set; }
        public int? DonLiReopVascDt { get; set; }
        public string DonLiVascCompl { get; set; }
        public int? DonLiVascComplIntervention { get; set; }
        public int? DonLuArrhythm { get; set; }
        public int? DonLuCapacityPreop { get; set; }
        public string DonLuCompl { get; set; }
        public int? DonLuComplReason { get; set; }
        public string DonLuProcedureConvert { get; set; }
        public int? DonLuProcedureTy { get; set; }
        public string DonLuReadmit { get; set; }
        public int? DonLuReadmitDt { get; set; }
        public int? DonLuReadmitReason { get; set; }
        public int? DonLuThoracTubes { get; set; }
        public int? DonMaritalStat { get; set; }
        public string DonMedicaid { get; set; }
        public string DonMedicare { get; set; }
        public string DonNonAutoBlood { get; set; }
        public int? DonOpoRunMatch { get; set; }
        public string DonOrg1 { get; set; }
        public string DonOrg2 { get; set; }
        public string DonOtherGovt { get; set; }
        public string DonOtherTobaccoUse { get; set; }
        public int? DonPackYears { get; set; }
        public int? DonPao2Preop { get; set; }
        public int? DonPhyscCapacity { get; set; }
        public int? DonPltUnits { get; set; }
        public int? DonPostopTestDt { get; set; }
        public int? DonPrbcUnits { get; set; }
        public int? DonPrimaryPay { get; set; }
        public string DonPrivInsur { get; set; }
        public int? DonRace { get; set; }
        public string DonRaceSrtr { get; set; }
        public int? DonRecovDt { get; set; }
        public string DonRecovTxSameCtr { get; set; }
        public int? DonRelationshipTy { get; set; }
        public int? DonSacrificeLobe { get; set; }
        public string DonSelf { get; set; }
        public int? DonSgotPostop { get; set; }
        public int? DonSgotPreop { get; set; }
        public int? DonSgptPostop { get; set; }
        public int? DonSgptPreop { get; set; }
        public string DonStat { get; set; }
        public int? DonStatDt { get; set; }
        public int? DonTargetSource1 { get; set; }
        public int? DonTargetSource2 { get; set; }
        public int? DonTlcAfterPreop { get; set; }
        public int? DonTlcBeforePreop { get; set; }
        public string DonTy { get; set; }
        public int? DonTypMethclass1 { get; set; }
        public int? DonTypMethclass1Dt { get; set; }
        public int? DonTypMethclass2 { get; set; }
        public int? DonTypMethclass2Dt { get; set; }
        public int? DonUrinePostopProtein { get; set; }
        public int? DonUrinePostopRatio { get; set; }
        public int? DonUrinePreopProtein { get; set; }
        public int? DonUrinePreopRatio { get; set; }
        public string DonVirusesTested { get; set; }
        public int? DonWgtKg { get; set; }
        public string DonWorkIncome { get; set; }
        public int? DonWorkNoStat { get; set; }
        public int? DonWorkYesStat { get; set; }
        public int? DonYearEntryUs { get; set; }
        public int PersId { get; set; }
        public int? PersSsaDeathDt { get; set; }

        public virtual Donor Donor { get; set; }
    }
}
