using System;
using System.Collections.Generic;

namespace csc424_se2_organApp.Models
{
    public partial class DonorDeceased
    {
        public int DonorId { get; set; }
        public int? DonA1 { get; set; }
        public int? DonA2 { get; set; }
        public string DonAbnormCongen { get; set; }
        public string DonAbnormLvh { get; set; }
        public string DonAbnormValves { get; set; }
        public string DonAbo { get; set; }
        public int? DonAge { get; set; }
        public int? DonAgeInMonths { get; set; }
        public int? DonAllocEcdCva { get; set; }
        public int? DonAllocEcdHyperten { get; set; }
        public int? DonAllocEcdSerumCreat { get; set; }
        public int? DonAllocEcdSerumCreatDt { get; set; }
        public string DonAllocRemainLiSeg { get; set; }
        public string DonAntiCmv { get; set; }
        public string DonAntiConvuls { get; set; }
        public string DonAntiHbc { get; set; }
        public string DonAntiHcv { get; set; }
        public string DonAntiHiv { get; set; }
        public string DonAntiHtlv { get; set; }
        public string DonAntiHyperten { get; set; }
        public string DonArginine { get; set; }
        public int? DonB1 { get; set; }
        public int? DonB2 { get; set; }
        public int? DonBiopsyDgn { get; set; }
        public int? DonBrainDeathTm { get; set; }
        public int? DonBun { get; set; }
        public int? DonBw4 { get; set; }
        public int? DonBw6 { get; set; }
        public int? DonC1 { get; set; }
        public int? DonC2 { get; set; }
        public int? DonCadDonCod { get; set; }
        public int? DonCancerFreeInterval { get; set; }
        public string DonCancerOtherOstxt { get; set; }
        public string DonCardiacArrestAfterDeath { get; set; }
        public string DonChagasNat { get; set; }
        public int? DonChestXray { get; set; }
        public int? DonCitizenship { get; set; }
        public int? DonCiFinal { get; set; }
        public int? DonCiInit { get; set; }
        public int? DonClampDt { get; set; }
        public int? DonClampTm { get; set; }
        public int? DonClampTmZone { get; set; }
        public string DonClinicalInfect { get; set; }
        public int? DonCodDonStroke { get; set; }
        public int? DonColdIschTmArrivKi { get; set; }
        public int? DonConsentAttorney { get; set; }
        public int? DonConsentDonCard { get; set; }
        public int? DonConsentDonRegis { get; set; }
        public int? DonConsentDriverLicense { get; set; }
        public string DonConsentPxWritDoc { get; set; }
        public int? DonConsentTm { get; set; }
        public string DonConsentWritDocIntent { get; set; }
        public string DonContAlcohol { get; set; }
        public string DonContCigarette { get; set; }
        public string DonContCocaine { get; set; }
        public string DonContIvDrug { get; set; }
        public string DonContOtherDrug { get; set; }
        public int? DonCoronaryAngio { get; set; }
        public int? DonCoFinal { get; set; }
        public int? DonCoInit { get; set; }
        public int? DonCreat { get; set; }
        public int? DonCregDonFlg { get; set; }
        public int? DonCvpFinal { get; set; }
        public int? DonCvpInit { get; set; }
        public int? DonDcdAbdomAortaCannulDt { get; set; }
        public int? DonDcdAbdomAortaCannulTm { get; set; }
        public int? DonDcdAgonalBeginDt { get; set; }
        public int? DonDcdAgonalBeginTm { get; set; }
        public int? DonDcdPortalVeinCannulDt { get; set; }
        public int? DonDcdPortalVeinCannulTm { get; set; }
        public string DonDcdProgressToBrainDeath { get; set; }
        public int? DonDcdPulmArtCannulDt { get; set; }
        public int? DonDcdPulmArtCannulTm { get; set; }
        public int? DonDcdSupportWithdrawDt { get; set; }
        public int? DonDcdSupportWithdrawTm { get; set; }
        public int? DonDcdThorAortaCannulDt { get; set; }
        public int? DonDcdThorAortaCannulTm { get; set; }
        public int? DonDcdTotUrineOutput { get; set; }
        public string DonDdavp { get; set; }
        public int? DonDeathCircum { get; set; }
        public int? DonDeathMech { get; set; }
        public string DonDobutamine { get; set; }
        public string DonDopamine { get; set; }
        public int? DonDp1 { get; set; }
        public int? DonDp2 { get; set; }
        public int? DonDq1 { get; set; }
        public int? DonDq2 { get; set; }
        public int? DonDr1 { get; set; }
        public int? DonDr2 { get; set; }
        public int? DonDr51 { get; set; }
        public int? DonDr52 { get; set; }
        public int? DonDr53 { get; set; }
        public string DonEbna { get; set; }
        public string DonEbvIgg { get; set; }
        public string DonEbvIgm { get; set; }
        public int? DonEjectFract { get; set; }
        public int? DonEjectFractMeth { get; set; }
        public string DonEthnicitySrtr { get; set; }
        public int? DonExpandDonFlgOptn { get; set; }
        public int? DonExpandDonKi { get; set; }
        public string DonExpressFamily { get; set; }
        public string DonExtracranialCancer { get; set; }
        public int? DonFeedbackDone { get; set; }
        public int? DonFinalSerumCreat { get; set; }
        public string DonGender { get; set; }
        public int? DonHbcStat { get; set; }
        public string DonHbvNat { get; set; }
        public string DonHbvSurfAntibody { get; set; }
        public string DonHbvSurfAntigen { get; set; }
        public string DonHcvNat { get; set; }
        public int? DonHcvStat { get; set; }
        public string DonHeavyAlcohol { get; set; }
        public int? DonHematocrit { get; set; }
        public string DonHeparin { get; set; }
        public int? DonHgtCm { get; set; }
        public int? DonHighCreat { get; set; }
        public string DonHistAlcohol { get; set; }
        public int? DonHistCancer { get; set; }
        public string DonHistCigaretteGt20Pkyr { get; set; }
        public string DonHistCocaine { get; set; }
        public int? DonHistDiab { get; set; }
        public int? DonHistHyperten { get; set; }
        public int? DonHistInsulinDepnd { get; set; }
        public string DonHistIvDrug { get; set; }
        public string DonHistOtherDrug { get; set; }
        public string DonHistPrevMi { get; set; }
        public string DonHivNat { get; set; }
        public string DonHlaTyp { get; set; }
        public int? DonHlaTypNotDone { get; set; }
        public string DonHomeState { get; set; }
        public string DonHtlvNat { get; set; }
        public int? DonHtn { get; set; }
        public string DonHypertenDiet { get; set; }
        public string DonHypertenDiuretics { get; set; }
        public string DonHypertenOtherMeds { get; set; }
        public int? DonInfectBlood { get; set; }
        public string DonInfectBloodConfirm { get; set; }
        public int? DonInfectLu { get; set; }
        public string DonInfectLuConfirm { get; set; }
        public int? DonInfectOther { get; set; }
        public string DonInfectOtherConfirm { get; set; }
        public int? DonInfectUrine { get; set; }
        public string DonInfectUrineConfirm { get; set; }
        public string DonInotropAgentGe3 { get; set; }
        public string DonInotropSupport { get; set; }
        public int? DonInr { get; set; }
        public string DonInsulin { get; set; }
        public string DonIntracranialCancer { get; set; }
        public int? DonKiGlomerObserved { get; set; }
        public int? DonKiGlomerSclerPct { get; set; }
        public string DonLfKiBiopsy { get; set; }
        public int? DonLfKiGlomerSclerPct { get; set; }
        public string DonLfKiPump { get; set; }
        public int? DonLfKiResistPriorShip { get; set; }
        public string DonLfKiTxferPump { get; set; }
        public int? DonLfLuBroncho { get; set; }
        public int? DonLipase { get; set; }
        public string DonLiBiopsy { get; set; }
        public int? DonLiBiopsyMacroFat { get; set; }
        public int? DonLiBiopsyMicroFat { get; set; }
        public int? DonLiOthHistologyGranulomas { get; set; }
        public int? DonLiOthHistologyHemosidera { get; set; }
        public int? DonLiOthHistologyOther { get; set; }
        public int? DonMapFinal { get; set; }
        public int? DonMapInit { get; set; }
        public int? DonMaxCreat { get; set; }
        public int? DonMedExaminer { get; set; }
        public string DonMeetCdcHighRisk { get; set; }
        public int? DonMeetDoubleKiCrit { get; set; }
        public string DonNonHrBeat { get; set; }
        public string DonNonHrBeatCntl { get; set; }
        public string DonNonHrBeatCoreCool { get; set; }
        public int? DonOpoCtrId { get; set; }
        public int? DonPaDiastFinal { get; set; }
        public int? DonPaDiastInit { get; set; }
        public int? DonPaSystFinal { get; set; }
        public int? DonPaSystInit { get; set; }
        public int? DonPco2 { get; set; }
        public int? DonPcwpFinal { get; set; }
        public int? DonPcwpInit { get; set; }
        public int? DonPeakSerumCreat { get; set; }
        public int? DonPh { get; set; }
        public int? DonPo2 { get; set; }
        public string DonPo2Done { get; set; }
        public int? DonPo2Fio2 { get; set; }
        public string DonPrerecovDiuretics { get; set; }
        public string DonPrerecovMeds { get; set; }
        public string DonPrerecovSteroids { get; set; }
        public string DonPrerecovT3 { get; set; }
        public string DonPrerecovT4 { get; set; }
        public string DonPrevGastroDisease { get; set; }
        public string DonProteinUrine { get; set; }
        public string DonPulmCath { get; set; }
        public int? DonRace { get; set; }
        public string DonRaceSrtr { get; set; }
        public int? DonRecovDt { get; set; }
        public string DonRecovOutUs { get; set; }
        public int? DonRefDt { get; set; }
        public string DonRefFlg { get; set; }
        public int? DonResuscitDuration { get; set; }
        public string DonRprVdrl { get; set; }
        public string DonRtKiBiopsy { get; set; }
        public int? DonRtKiGlomerSclerPct { get; set; }
        public string DonRtKiPump { get; set; }
        public int? DonRtKiResistPriorShip { get; set; }
        public string DonRtKiTxferPump { get; set; }
        public int? DonRtLuBroncho { get; set; }
        public int? DonSerumAmylase { get; set; }
        public int? DonSgot { get; set; }
        public int? DonSgpt { get; set; }
        public string DonSkinCancer { get; set; }
        public int? DonSodium { get; set; }
        public int? DonSvrFinal { get; set; }
        public int? DonSvrInit { get; set; }
        public int? DonTargetSource1 { get; set; }
        public int? DonTargetSource2 { get; set; }
        public string DonTattoos { get; set; }
        public string DonTmForXmatch { get; set; }
        public int? DonTotBili { get; set; }
        public int? DonTx { get; set; }
        public int? DonTxfusTerminalHospNum { get; set; }
        public string DonTy { get; set; }
        public int? DonTypMethclass1 { get; set; }
        public int? DonTypMethclass1Dt { get; set; }
        public int? DonTypMethclass2 { get; set; }
        public int? DonTypMethclass2Dt { get; set; }
        public string DonUseDoubleKi { get; set; }
        public string DonVasodil { get; set; }
        public int? DonVesselsGt50Stenosis { get; set; }
        public string DonWallAbnormGlob { get; set; }
        public string DonWallAbnormSeg { get; set; }
        public int? DonWarmIschTmMins { get; set; }
        public string DonWestNileNat { get; set; }
        public int? DonWgtKg { get; set; }
        public int PersId { get; set; }

        public virtual Institution DonOpoCtr { get; set; }
        public virtual Donor Donor { get; set; }
    }
}
