using System;
using System.Collections.Generic;

namespace csc424_se2_organApp.Models
{
    public partial class TxLi
    {
        public double? CanhxMpxcptHccApplyInd { get; set; }
        public double? CanhxMpxcptHccApproveInd { get; set; }
        public string CanAbo { get; set; }
        public decimal? CanAgeAtListing { get; set; }
        public double? CanAgeInMonthsAtListing { get; set; }
        public decimal? CanAngina { get; set; }
        public decimal? CanAnginaCad { get; set; }
        public string CanBacteriaPerit { get; set; }
        public string CanCerebVasc { get; set; }
        public decimal? CanCitizenship { get; set; }
        public decimal? CanDgn { get; set; }
        public decimal? CanDgn2 { get; set; }
        public decimal? CanDiab { get; set; }
        public decimal? CanDiabTy { get; set; }
        public string CanDrugTreatCopd { get; set; }
        public string CanDrugTreatHyperten { get; set; }
        public decimal? CanEducation { get; set; }
        public string CanEthnicitySrtr { get; set; }
        public string CanGender { get; set; }
        public double? CanHgtCm { get; set; }
        public decimal? CanInitActStatCd { get; set; }
        public DateTime? CanInitActStatDt { get; set; }
        public DateTime? CanInitInactStatDt { get; set; }
        public decimal? CanInitSrtrLabMeld { get; set; }
        public string CanInitSrtrLabMeldTy { get; set; }
        public decimal? CanInitStat { get; set; }
        public DateTime? CanLastActStatDt { get; set; }
        public double? CanLastAlbumin { get; set; }
        public decimal? CanLastAscites { get; set; }
        public double? CanLastBili { get; set; }
        public string CanLastDialPriorWeek { get; set; }
        public decimal? CanLastEnceph { get; set; }
        public DateTime? CanLastInactStatDt { get; set; }
        public double? CanLastInr { get; set; }
        public double? CanLastSerumCreat { get; set; }
        public double? CanLastSerumSodium { get; set; }
        public decimal? CanLastSrtrLabMeld { get; set; }
        public string CanLastSrtrLabMeldTy { get; set; }
        public decimal? CanLastStat { get; set; }
        public DateTime? CanListingDt { get; set; }
        public string CanMalig { get; set; }
        public decimal? CanPepticUlcer { get; set; }
        public string CanPeriphVasc { get; set; }
        public string CanPortalVein { get; set; }
        public string CanPrevAbdomSurg { get; set; }
        public double? CanPrevHl { get; set; }
        public double? CanPrevHr { get; set; }
        public double? CanPrevIn { get; set; }
        public double? CanPrevKi { get; set; }
        public double? CanPrevKp { get; set; }
        public double? CanPrevLi { get; set; }
        public double? CanPrevLu { get; set; }
        public double? CanPrevPa { get; set; }
        public double? CanPrevTx { get; set; }
        public string CanPrevTxfus { get; set; }
        public string CanPulmEmbol { get; set; }
        public decimal? CanRace { get; set; }
        public string CanRaceSrtr { get; set; }
        public decimal? CanRemCd { get; set; }
        public string CanSource { get; set; }
        public string CanTipss { get; set; }
        public double? CanTotAlbumin { get; set; }
        public double? CanWgtKg { get; set; }
        public decimal? DonorId { get; set; }
        public double? DonorIdVessel { get; set; }
        public decimal? DonA1 { get; set; }
        public decimal? DonA2 { get; set; }
        public string DonAbo { get; set; }
        public double? DonAge { get; set; }
        public double? DonAgeInMonths { get; set; }
        public string DonAntiCmv { get; set; }
        public string DonAntiHcv { get; set; }
        public decimal? DonB1 { get; set; }
        public decimal? DonB2 { get; set; }
        public decimal? DonCadDonCod { get; set; }
        public string DonCardiacArrestAfterDeath { get; set; }
        public decimal? DonCitizenship { get; set; }
        public string DonCmvIgg { get; set; }
        public decimal? DonCodDonStroke { get; set; }
        public string DonContCigarette { get; set; }
        public string DonContCocaine { get; set; }
        public string DonContIvDrug { get; set; }
        public string DonContOtherDrug { get; set; }
        public double? DonCreat { get; set; }
        public string DonDdavp { get; set; }
        public decimal? DonDeathCircum { get; set; }
        public decimal? DonDeathMech { get; set; }
        public string DonDobutamine { get; set; }
        public string DonDopamine { get; set; }
        public decimal? DonDr1 { get; set; }
        public decimal? DonDr2 { get; set; }
        public string DonEthnicitySrtr { get; set; }
        public decimal? DonExpandDonKi { get; set; }
        public string DonGender { get; set; }
        public decimal? DonHaploTyMatch { get; set; }
        public double? DonHgtCm { get; set; }
        public decimal? DonHighCreat { get; set; }
        public decimal? DonHistCancer { get; set; }
        public string DonHistCigaretteGt20Pkyr { get; set; }
        public string DonHistCocaine { get; set; }
        public decimal? DonHistDiab { get; set; }
        public decimal? DonHistHyperten { get; set; }
        public string DonHistIvDrug { get; set; }
        public string DonHistOtherDrug { get; set; }
        public decimal? DonHtn { get; set; }
        public string DonInotropAgentGe3 { get; set; }
        public string DonInotropSupport { get; set; }
        public string DonInsulin { get; set; }
        public decimal? DonLivingDonCod { get; set; }
        public string DonLiBiopsy { get; set; }
        public string DonMeetCdcHighRisk { get; set; }
        public string DonNonHrBeat { get; set; }
        public decimal? DonOpoCtrId { get; set; }
        public double? DonOrgShared { get; set; }
        public double? DonPh { get; set; }
        public string DonPrerecovDiuretics { get; set; }
        public decimal? DonRace { get; set; }
        public string DonRaceSrtr { get; set; }
        public DateTime? DonRecovDt { get; set; }
        public decimal? DonRelationshipTy { get; set; }
        public double? DonSgot { get; set; }
        public double? DonSgotPreop { get; set; }
        public double? DonSgptPreop { get; set; }
        public string DonTy { get; set; }
        public double? DonWarmIschTmMins { get; set; }
        public double? DonWgtKg { get; set; }
        public string OrgAr { get; set; }
        public string OrgTy { get; set; }
        public decimal? PersId { get; set; }
        public decimal? PersOptnCod { get; set; }
        public DateTime? PersOptnDeathDt { get; set; }
        public DateTime? PersRelist { get; set; }
        public DateTime? PersRestrictDeathDt { get; set; }
        public string PersRestrictDeathVrfy { get; set; }
        public DateTime? PersRetx { get; set; }
        public decimal? PersRetxTrrId { get; set; }
        public DateTime? PersSsaDeathDt { get; set; }
        public decimal? PxId { get; set; }
        public decimal? RecA1 { get; set; }
        public decimal? RecA2 { get; set; }
        public decimal? RecAcademicLevel { get; set; }
        public decimal? RecAcademicProgress { get; set; }
        public decimal? RecAcuteRejBiopsyConfirmed { get; set; }
        public decimal? RecAcuteRejEpisode { get; set; }
        public DateTime? RecAdmissionDt { get; set; }
        public decimal? RecAgeAtTx { get; set; }
        public double? RecAgeInMonthsAtTx { get; set; }
        public string RecAntivrlTherapy { get; set; }
        public decimal? RecAntivrlTherapyTy { get; set; }
        public decimal? RecAntivrlTherapyTyAcyclovir { get; set; }
        public decimal? RecAntivrlTherapyTyCytogam { get; set; }
        public decimal? RecAntivrlTherapyTyCytovene { get; set; }
        public decimal? RecAntivrlTherapyTyEpivir { get; set; }
        public decimal? RecAntivrlTherapyTyFluVac { get; set; }
        public decimal? RecAntivrlTherapyTyGamimune { get; set; }
        public decimal? RecAntivrlTherapyTyGammagard { get; set; }
        public decimal? RecAntivrlTherapyTyHbig { get; set; }
        public decimal? RecAntivrlTherapyTyOther { get; set; }
        public decimal? RecAntivrlTherapyTyValcyte { get; set; }
        public decimal? RecAntivrlTherapyTyValtrex { get; set; }
        public decimal? RecArtificialLi { get; set; }
        public string RecAscites { get; set; }
        public double? RecAMmEquivCur { get; set; }
        public double? RecAMmEquivTx { get; set; }
        public decimal? RecB1 { get; set; }
        public decimal? RecB2 { get; set; }
        public string RecBacteriaPerit { get; set; }
        public double? RecBmi { get; set; }
        public double? RecBMmEquivCur { get; set; }
        public double? RecBMmEquivTx { get; set; }
        public string RecCmvIgg { get; set; }
        public string RecCmvIgm { get; set; }
        public string RecCmvStat { get; set; }
        public decimal? RecCod { get; set; }
        public decimal? RecCod2 { get; set; }
        public decimal? RecCod3 { get; set; }
        public decimal? RecCognitiveDevelop { get; set; }
        public double? RecColdIschTm { get; set; }
        public decimal? RecCtrId { get; set; }
        public decimal? RecCurCtrId { get; set; }
        public string RecCurPxStat { get; set; }
        public decimal? RecDgn { get; set; }
        public decimal? RecDgn2 { get; set; }
        public string RecDgnOstxt { get; set; }
        public double? RecDischrgAlbumin { get; set; }
        public double? RecDischrgAlkphos { get; set; }
        public double? RecDischrgCreat { get; set; }
        public DateTime? RecDischrgDt { get; set; }
        public double? RecDischrgInr { get; set; }
        public DateTime? RecDischrgLabDt { get; set; }
        public double? RecDischrgSgot { get; set; }
        public double? RecDischrgSgpt { get; set; }
        public decimal? RecDr1 { get; set; }
        public decimal? RecDr2 { get; set; }
        public double? RecDrMmEquivCur { get; set; }
        public double? RecDrMmEquivTx { get; set; }
        public string RecEbvStat { get; set; }
        public decimal? RecEmplStatPre04 { get; set; }
        public string RecFailBiliary { get; set; }
        public DateTime? RecFailDt { get; set; }
        public string RecFailHepDenovo { get; set; }
        public string RecFailHepRecur { get; set; }
        public string RecFailInfect { get; set; }
        public string RecFailPrimeGraftFail { get; set; }
        public string RecFailRecurDisease { get; set; }
        public string RecFailRejAcute { get; set; }
        public string RecFailVascThromb { get; set; }
        public decimal? RecFunctnStat { get; set; }
        public string RecGraftStat { get; set; }
        public string RecHbvAntibody { get; set; }
        public string RecHbvSurfAntigen { get; set; }
        public string RecHcvStat { get; set; }
        public string RecHepaticArterThromb { get; set; }
        public string RecHepaticOutflowObstruct { get; set; }
        public double? RecHgtCm { get; set; }
        public DateTime? RecHgtWgtDt { get; set; }
        public decimal? RecHistoTxId { get; set; }
        public string RecHivStat { get; set; }
        public string RecHosp90Days { get; set; }
        public string RecImmunoMaintMeds { get; set; }
        public string RecInotropBpSupport { get; set; }
        public string RecLifeSupport { get; set; }
        public decimal? RecLifeSupportOther { get; set; }
        public decimal? RecLiTy { get; set; }
        public string RecMalig { get; set; }
        public decimal? RecMaligTy { get; set; }
        public decimal? RecMaligTyBreast { get; set; }
        public decimal? RecMaligTyCnsTumor { get; set; }
        public decimal? RecMaligTyGenitourinary { get; set; }
        public decimal? RecMaligTyHepblast { get; set; }
        public decimal? RecMaligTyHepcarcinoma { get; set; }
        public decimal? RecMaligTyLeukLymph { get; set; }
        public decimal? RecMaligTyLiver { get; set; }
        public decimal? RecMaligTyLu { get; set; }
        public decimal? RecMaligTyOther { get; set; }
        public decimal? RecMaligTySkinMel { get; set; }
        public decimal? RecMaligTySkinNonMel { get; set; }
        public decimal? RecMaligTyThroat { get; set; }
        public decimal? RecMaligTyThyroid { get; set; }
        public decimal? RecMaligTyUnk { get; set; }
        public decimal? RecMedCond { get; set; }
        public double? RecMmEquivCur { get; set; }
        public double? RecMmEquivTx { get; set; }
        public decimal? RecMotorDevelop { get; set; }
        public string RecOnVentilator { get; set; }
        public decimal? RecOpoId { get; set; }
        public string RecOtherTherapy { get; set; }
        public decimal? RecOtherTherapyTy { get; set; }
        public decimal? RecOtherTherapyTyPhotoph { get; set; }
        public decimal? RecOtherTherapyTyPlasmaph { get; set; }
        public decimal? RecOtherTherapyTyTli { get; set; }
        public string RecPbCredit { get; set; }
        public string RecPbDebt { get; set; }
        public decimal? RecPbShareTy { get; set; }
        public string RecPermState { get; set; }
        public decimal? RecPhyscCapacity { get; set; }
        public string RecPortalHypertenBleed { get; set; }
        public string RecPortalVein { get; set; }
        public string RecPortalVeinThromb { get; set; }
        public double? RecPostxLos { get; set; }
        public double? RecPretxAlbumin { get; set; }
        public double? RecPretxCreat { get; set; }
        public double? RecPretxInr { get; set; }
        public DateTime? RecPretxLabDt { get; set; }
        public double? RecPretxTotBili { get; set; }
        public string RecPrevAbdomSurg { get; set; }
        public double? RecPrevHl { get; set; }
        public double? RecPrevHr { get; set; }
        public double? RecPrevIn { get; set; }
        public double? RecPrevKi { get; set; }
        public double? RecPrevKp { get; set; }
        public double? RecPrevLi { get; set; }
        public double? RecPrevLu { get; set; }
        public string RecPrevNonfunctnTx { get; set; }
        public double? RecPrevPa { get; set; }
        public decimal? RecPrimaryPay { get; set; }
        public string RecProcedureTyLi { get; set; }
        public string RecPxResearch { get; set; }
        public string RecPxStat { get; set; }
        public DateTime? RecPxStatDt { get; set; }
        public decimal? RecSecondaryPay { get; set; }
        public double? RecSgpt { get; set; }
        public string RecTipss { get; set; }
        public string RecToleranceInductionTech { get; set; }
        public string RecTumor { get; set; }
        public decimal? RecTumorTy { get; set; }
        public decimal? RecTxferCtrId { get; set; }
        public DateTime? RecTxferDt { get; set; }
        public DateTime? RecTxDt { get; set; }
        public string RecTxExtraVessel { get; set; }
        public string RecTxOrgTy { get; set; }
        public decimal? RecTxProcedureTy { get; set; }
        public decimal? RecTxTy { get; set; }
        public string RecValcyte { get; set; }
        public string RecVaricealBleeding { get; set; }
        public decimal? RecVentilator { get; set; }
        public double? RecWarmIschTm { get; set; }
        public double? RecWgtKg { get; set; }
        public string RecWorkIncome { get; set; }
        public decimal? RecWorkNoStat { get; set; }
        public decimal? RecWorkYesStat { get; set; }
        public decimal? TflCod { get; set; }
        public DateTime? TflDeathDt { get; set; }
        public DateTime? TflEndtxfu { get; set; }
        public DateTime? TflGraftDt { get; set; }
        public DateTime? TflLafudate { get; set; }
        public string TflLastatus { get; set; }
        public decimal TrrId { get; set; }
        public decimal TxId { get; set; }
    }
}
